# Generated by Django 5.0.6 on 2024-06-07 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время когда выполняется привычка')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность в днях')),
                ('reward', models.CharField(max_length=150, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение (минуты)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
