# Generated by Django 5.0.6 on 2024-06-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение'),
        ),
    ]
